// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// logdmultinomCPP
double logdmultinomCPP(Rcpp::NumericMatrix x, double size, Rcpp::NumericMatrix prob);
RcppExport SEXP _IlesShowUSomething_logdmultinomCPP(SEXP xSEXP, SEXP sizeSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(logdmultinomCPP(x, size, prob));
    return rcpp_result_gen;
END_RCPP
}
// nll_fun
double nll_fun(Rcpp::NumericVector params, arma::mat X1, arma::mat X2, Rcpp::StringVector tau_params, int nsurvey, arma::cube Yarray, arma::mat tarray, arma::mat rarray, Rcpp::NumericVector nrint, Rcpp::NumericVector ntint, Rcpp::NumericVector max_r, Rcpp::NumericVector Ysum, Rcpp::NumericVector nlimit);
RcppExport SEXP _IlesShowUSomething_nll_fun(SEXP paramsSEXP, SEXP X1SEXP, SEXP X2SEXP, SEXP tau_paramsSEXP, SEXP nsurveySEXP, SEXP YarraySEXP, SEXP tarraySEXP, SEXP rarraySEXP, SEXP nrintSEXP, SEXP ntintSEXP, SEXP max_rSEXP, SEXP YsumSEXP, SEXP nlimitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type tau_params(tau_paramsSEXP);
    Rcpp::traits::input_parameter< int >::type nsurvey(nsurveySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Yarray(YarraySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type tarray(tarraySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rarray(rarraySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type nrint(nrintSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ntint(ntintSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type max_r(max_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ysum(YsumSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type nlimit(nlimitSEXP);
    rcpp_result_gen = Rcpp::wrap(nll_fun(params, X1, X2, tau_params, nsurvey, Yarray, tarray, rarray, nrint, ntint, max_r, Ysum, nlimit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IlesShowUSomething_logdmultinomCPP", (DL_FUNC) &_IlesShowUSomething_logdmultinomCPP, 3},
    {"_IlesShowUSomething_nll_fun", (DL_FUNC) &_IlesShowUSomething_nll_fun, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_IlesShowUSomething(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
