# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Negative log likelihood function
#' 
#' A function to calculate negative log likelihood.
#'
#' @param params
#' @param X1
#' @param X2
#' @param tau_params
#' @param nsurvey
#' @param Yarray
#' @param tarray
#' @param rarray
#' @param nrint
#' @param ntint
#' @param max_r
#' @param Ysum
#' @param nlimit
NULL

#' logdmultinomCPP
#' 
#' A function to calculate log density
#' of multinomial.
#'
#' @param x A matrix
#' @param size A double
#' @param prob A Matrix
#' @export
logdmultinomCPP <- function(x, size, prob) {
    .Call(`_cmult_joint_dev_logdmultinomCPP`, x, size, prob)
}

optim_rcpp <- function(params, X1, X2, tau_params, nsurvey, Yarray, tarray, rarray, nrint, ntint, max_r, Ysum, nlimit, method) {
    .Call(`_cmult_joint_dev_optim_rcpp`, params, X1, X2, tau_params, nsurvey, Yarray, tarray, rarray, nrint, ntint, max_r, Ysum, nlimit, method)
}

runit <- function(k, Yarray, nrint, ntint) {
    .Call(`_cmult_joint_dev_runit`, k, Yarray, nrint, ntint)
}

